spring.application.name=flow-control-badaruco

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.springframework.jdbc=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.flyway.enabled=false

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=2  

spring.datasource.url=jdbc:postgresql://localhost:5432/flow_control_badaruco
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#spring.jpa.hibernate.ddl-auto=validate

